---
collections:
  - name: ansible.posix
    version: "==1.6.2"
  - name: community.general
    version: "==10.7.7"
  - name: community.docker
    version: ">=3.4.0"
  - name: cloud.terraform
    version: "==2.1.0"
