---
collections:
  - name: ansible.posix
    version: "==2.1.0"
  - name: community.general
    version: "==12.3.0"
  - name: community.docker
    version: ">=3.4.0"
  - name: cloud.terraform
    version: "==4.0.0"
