---
collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=8.0.0"

# For production: pin to specific versions
# - name: community.general
#   version: "==5.8.0"
