---
collections:
  - name: ansible.posix
    version: "==1.6.2"
  - name: community.general
    version: "==10.3.0"
  - name: community.docker
    version: "==3.4.8"
  - name: cloud.terraform
    version: "==2.2.1"
