---
all:
  children:
    splunk:
      hosts:
        splunk-01:
          ansible_host: "{{ lookup('env', 'SPLUNK_VM_HOST') }}"
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
