---
# Pre-playbook that loads Terraform infrastructure data dynamically
# This playbook runs first to populate the Ansible inventory from Terraform outputs,
# eliminating hardcoded VM IPs from Ansible configuration.
#
# It expects terraform_inventory.json to be present (generated via:
#   ./scripts/sync-terraform-inventory.sh
# or manually:
#   cd ~/git/terraform-proxmox/main && terragrunt output -json ansible_inventory > \
#     ~/git/ansible-splunk/inventory/terraform_inventory.json

- name: Load Terraform Infrastructure Inventory
  hosts: localhost
  gather_facts: false
  become: false

  tasks:
    - name: Check if Terraform inventory file exists
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/../inventory/terraform_inventory.json"
      register: terraform_inventory_file

    - name: Load Terraform inventory JSON
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../inventory/terraform_inventory.json"
        name: terraform_data
      when: terraform_inventory_file.stat.exists

    - name: Fail if Terraform inventory is missing in production
      ansible.builtin.fail:
        msg: |
          terraform_inventory.json not found at {{ playbook_dir }}/../inventory/terraform_inventory.json

          To generate it, run:
            ./scripts/sync-terraform-inventory.sh

          Or manually:
            cd ~/git/terraform-proxmox/main && \
            terragrunt output -json ansible_inventory > \
            ~/git/ansible-splunk/inventory/terraform_inventory.json

          For static inventory fallback, ensure SPLUNK_VM_HOST environment variable is set:
            export SPLUNK_VM_HOST="splunk.example.com"
      when: not terraform_inventory_file.stat.exists and not (lookup('env', 'SPLUNK_VM_HOST') | default(''))

    - name: Add Splunk VM to inventory (SSH connection)
      ansible.builtin.add_host:
        name: splunk
        groups:
          - splunk
          - all
        ansible_host: "{{ terraform_data.splunk_vm.splunk.ip }}"
        ansible_connection: "{{ terraform_data.splunk_vm.splunk.ansible_connection | default('ssh') }}"
        # NOTE:
        #   The 'debian' user must have passwordless sudo on the target host.
        #   Downstream playbooks (e.g. deploy_docker.yml) use 'become: true'
        #   and rely on this user being able to escalate privileges via sudo
        #   without requiring an interactive password.
        ansible_user: debian
        ansible_ssh_private_key_file: "{{ lookup('env', 'PROXMOX_SSH_KEY_PATH') }}"
        ansible_python_interpreter: /usr/bin/python3
        hostname: "{{ terraform_data.splunk_vm.splunk.hostname }}"
        vmid: "{{ terraform_data.splunk_vm.splunk.vmid }}"
      when: terraform_inventory_file.stat.exists and terraform_data.splunk_vm.splunk is defined
