---
# Molecule converge playbook
# Tests the splunk_docker role against the test container

- name: Converge
  hosts: all
  become: true
  gather_facts: true

  vars:
    # Test values - override role defaults for testing
    splunk_docker_password: "molecule-test-password"
    splunk_docker_hec_token: "molecule-test-hec-token"
    # Use test image
    splunk_docker_image: splunk/splunk:latest

  tasks:
    - name: Include splunk_docker role
      ansible.builtin.include_role:
        name: splunk_docker
