---
# Molecule converge playbook
# Tests the splunk_docker role against the test container

- name: Converge
  hosts: all
  become: true
  gather_facts: true

  vars:
    # Test values - override role defaults for testing
    splunk_docker_password: "molecule-test-password"
    splunk_docker_hec_namespace: "12345678-1234-1234-1234-123456789abc"
    # Token values will be derived in site.yml from namespace.
    # For direct role testing, provide pre-computed values:
    splunk_docker_hec_token_values:
      ai: "molecule-test-token-ai"
      claude: "molecule-test-token-claude"
      firewall: "molecule-test-token-firewall"
      netflow: "molecule-test-token-netflow"
      network: "molecule-test-token-network"
      otel: "molecule-test-token-otel"
      os: "molecule-test-token-os"
      unifi: "molecule-test-token-unifi"
      legacy: "molecule-test-token-legacy"
    # Use test image
    splunk_docker_image: splunk/splunk:latest

  tasks:
    - name: Include splunk_docker role
      ansible.builtin.include_role:
        name: splunk_docker
