---
dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/requirements.yml

driver:
  name: docker

platforms:
  - name: splunk-test
    image: geerlingguy/docker-debian12-ansible:latest
    privileged: true
    command: ""
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    groups:
      - splunk
    docker_networks:
      - name: splunk_network

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles
  inventory:
    group_vars:
      all:
        # Test values for molecule - override in production
        splunk_docker_password: "molecule-test-password"
        splunk_docker_hec_token: "molecule-test-hec-token"
        # App archives are gitignored (placed manually at deploy time).
        # Setting these here prevents include_vars from loading the registry
        # and trying to validate missing archive files in CI.
        splunk_docker_apps: []
        splunk_docker_custom_addons: []
  env:
    SPLUNK_DOCKER_PASSWORD: "molecule-test-password"
    SPLUNK_DOCKER_HEC_TOKEN: "molecule-test-hec-token"

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
