---
# Molecule preparation playbook
# Sets up the test container before running the splunk_docker role

- name: Prepare
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Wait for container to be ready
      ansible.builtin.wait_for_connection:
        timeout: 30

    - name: Gather facts
      ansible.builtin.setup:

    - name: Update apt cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Install base packages for Docker role
      ansible.builtin.apt:
        name:
          - curl
          - gnupg
          - ca-certificates
          - procps
          - systemd
          - iptables
          - python3-requests
        state: present
      when: ansible_os_family == 'Debian'

    - name: Create Docker config directory
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        mode: "0755"

    - name: Configure Docker to use vfs storage driver
      ansible.builtin.copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "storage-driver": "vfs"
          }
        mode: "0644"
