---
# Molecule verification playbook
# Validates that the splunk_docker role executed correctly

- name: Verify
  hosts: all
  become: true
  gather_facts: true

  vars:
    splunk_docker_config_dir: /opt/splunk-config
    splunk_docker_etc_dir: /opt/splunk/etc

  tasks:
    - name: Check Splunk config directory exists
      ansible.builtin.stat:
        path: "{{ splunk_docker_config_dir }}"
      register: config_dir

    - name: Assert config directory exists
      ansible.builtin.assert:
        that:
          - config_dir.stat.exists
          - config_dir.stat.isdir
        fail_msg: "Splunk config directory not found at {{ splunk_docker_config_dir }}"

    - name: Check docker-compose.yml exists
      ansible.builtin.stat:
        path: "{{ splunk_docker_config_dir }}/docker-compose.yml"
      register: compose_file

    - name: Assert docker-compose.yml exists
      ansible.builtin.assert:
        that:
          - compose_file.stat.exists
        fail_msg: "docker-compose.yml not found - role did not deploy"

    - name: Check Splunk etc directory exists
      ansible.builtin.stat:
        path: "{{ splunk_docker_etc_dir }}"
      register: etc_dir

    - name: Assert Splunk etc directory exists
      ansible.builtin.assert:
        that:
          - etc_dir.stat.exists
          - etc_dir.stat.isdir
        fail_msg: "Splunk etc directory not found at {{ splunk_docker_etc_dir }}"

    - name: Check indexes.conf exists
      ansible.builtin.stat:
        path: "{{ splunk_docker_etc_dir }}/system/local/indexes.conf"
      register: indexes_conf

    - name: Assert indexes.conf configured
      ansible.builtin.assert:
        that:
          - indexes_conf.stat.exists
        fail_msg: "indexes.conf not found - indexes not configured"

    - name: Check web.conf exists
      ansible.builtin.stat:
        path: "{{ splunk_docker_etc_dir }}/system/local/web.conf"
      register: web_conf

    - name: Assert web.conf configured
      ansible.builtin.assert:
        that:
          - web_conf.stat.exists
        fail_msg: "web.conf not found - web interface not configured"

    - name: Check firewall script exists
      ansible.builtin.stat:
        path: "{{ splunk_docker_config_dir }}/firewall.sh"
      register: firewall_script

    - name: Assert firewall script configured
      ansible.builtin.assert:
        that:
          - firewall_script.stat.exists
        fail_msg: "firewall.sh not found - firewall not configured"

    - name: Check Splunk apps directory exists
      ansible.builtin.stat:
        path: "{{ splunk_docker_etc_dir }}/apps"
      register: apps_dir

    - name: Assert Splunk apps directory exists
      ansible.builtin.assert:
        that:
          - apps_dir.stat.exists
          - apps_dir.stat.isdir
        fail_msg: "Splunk apps directory not found"
